apiVersion: platform.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: yt-enricher
  namespace: flink
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  flinkEnvironment: yt-flink-env
  image: quay.io/osowski/yt-enricher:202605181540
  flinkVersion: v2_1
  serviceAccount: flink
  cmfRestClassRef:
    name: cmf-rest-class
    namespace: flink
  flinkConfiguration:
    state.backend.type: rocksdb
    state.backend.incremental: "true"
    execution.checkpointing.interval: "60000"
    execution.checkpointing.mode: EXACTLY_ONCE
    taskmanager.numberOfTaskSlots: "2"
    state.checkpoints.dir: "s3://warehouse/checkpoints/yt-enricher"
    state.savepoints.dir: "s3://warehouse/savepoints/yt-enricher"
    high-availability.storageDir: "s3://warehouse/ha/yt-enricher"
    s3.endpoint: "http://minio.storage.svc.cluster.local:9000"
    s3.path.style.access: "true"
    s3.connection.ssl.enabled: "false"
  jobManager:
    resource:
      cpu: 1
      memory: "1024m"
  taskManager:
    resource:
      cpu: 2
      memory: "2048m"
  job:
    jarURI: local:///opt/flink/usrlib/yt-enricher.jar
    entryClass: io.youtube.history.EnricherJob
    parallelism: 1
    state: running
    upgradeMode: savepoint
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          envFrom:
            - secretRef:
                name: yt-enricher-confluent-creds
            - configMapRef:
                name: yt-pipeline-config
          env:
            - name: ENABLE_BUILT_IN_PLUGINS
              value: "flink-s3-fs-hadoop-2.1.1-cp2.jar"
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: yt-youtube-api-key
                  key: YOUTUBE_API_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-password
