apiVersion: platform.confluent.io/v1beta1
kind: FlinkEnvironment
metadata:
  name: yt-flink-env
  namespace: flink
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  kubernetesNamespace: flink
  cmfRestClassRef:
    name: cmf-rest-class
    namespace: flink
  flinkApplicationDefaults:
    spec:
      flinkConfiguration:
        taskmanager.numberOfTaskSlots: "2"
        metrics.reporter.prom.factory.class: "org.apache.flink.metrics.prometheus.PrometheusReporterFactory"
        metrics.reporter.prom.port: "9249-9250"
        rest.profiling.enabled: "true"