apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yt-youtube-api-key
  namespace: flink
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: yt-youtube-api-key
    creationPolicy: Owner
  data:
    - secretKey: YOUTUBE_API_KEY
      remoteRef:
        key: /yt-pipeline/youtube/api-key
        property: api_key
